### ISSUE TITLE
Can data preprocessing be accelerated?

### ISSUE THREAD

**Issue by qiaozhijian** [johnwlambert/tbv#10]
Thanks for your great work. While model inference is fast, map and semantic image rendering is very slow. The preprocessing of the entire dataset cannot even be done in a few days. Will the data preprocessing code be further optimized?

**Comment by johnwlambert** [comment]
Certainly the map and semantic image rendering can be accelerated in many ways. The code for rendering is largely unoptimized currently (except for the CUDA ray-tracing routines). I welcome pull requests or contributions towards the following efforts:

1. **BEV image rendering**: I kept the resolution at 0.02 meter/pixel for the [BEV rendering configs](https://github.com/johnwlambert/tbv/blob/43059e507a017a4c513a411db2b3276a4bd68fdd/tbv/rendering_configs/52c611bd-50d1-47ee-aedf-3879958b243c.yaml#L25). At 20 meters in all directions, this leads to 40/0.02 = 2000 x 2000 pixel images. These high-res images were useful for data annotation, but are not needed for training, since we resize to 234 x 234 px anyways (see [config](https://github.com/johnwlambert/tbv/blob/main/tbv/training_configs/19180eb3-94a7-4d9c-b3c2-2ddc22cf9704.yaml#L25) and [transform](https://github.com/johnwlambert/tbv/blob/main/tbv/utils/tbv_transform.py#L346) code). By decreasing the resolution from 0.02 to something like 0.17 meters/px, you would get 235 x 235 images immediately from rendering, and likely get a ~10x speedup in the slow interpolation step of the rendering.
2. **Ego-view image rendering**: This code could be ported to OpenGL to make it run very fast.
3. **Map augmentations**: This code logic could be ported to C++ instead of Python, and wrapped with `pybind11`, to make it run very fast.

**Comment by qiaozhijian** [comment]
Thank you for your suggestions!
